%include "colon.inc"

section .data

colon "car", key_car
db "A four-wheeled motor vehicle used for transportation", 0

colon "dog", key_dog
db "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, non-retractable claws, and a barking, howling, or whining voice", 0

colon "house", key_house
db "A building for human habitation, especially one that is lived in by a family or small group of people", 0

colon "tree", key_tree
db "A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground", 0

colon "sun", key_sun
db "The star around which the earth orbits, providing light and heat", 0
